#!/usr/bin/env bash
# ward-duty local dev orchestrator.
#
# Usage:
#   scripts/dev.sh up        # PG + Redis + solver + api + web 모두 기동, prefix 로그
#   scripts/dev.sh down      # 모두 정지 (PG/Redis 컨테이너는 stop, 데이터는 보존)
#   scripts/dev.sh status    # 컨테이너 + 서비스 상태
#   scripts/dev.sh reset     # DB 데이터만 truncate (seed는 유지)
#   scripts/dev.sh purge     # 컨테이너 완전 삭제 (데이터 영구 손실)
#   scripts/dev.sh init      # 1회 셋업 (DB 생성 + 마이그 적용)

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PG_NAME=local-pg
REDIS_NAME=local-redis
PG_PASSWORD=local
DB_NAME=ward_duty

PIDS_FILE="$ROOT/.dev/pids"
mkdir -p "$ROOT/.dev"

# ----- colors -----
if [[ -t 1 ]]; then
  C_RED=$'\033[31m'; C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'
  C_BLUE=$'\033[34m'; C_PURPLE=$'\033[35m'; C_CYAN=$'\033[36m'
  C_DIM=$'\033[2m'; C_RESET=$'\033[0m'
else
  C_RED=""; C_GREEN=""; C_YELLOW=""; C_BLUE=""; C_PURPLE=""; C_CYAN=""; C_DIM=""; C_RESET=""
fi

info()  { printf "${C_CYAN}[dev]${C_RESET} %s\n" "$*"; }
warn()  { printf "${C_YELLOW}[dev]${C_RESET} %s\n" "$*"; }
err()   { printf "${C_RED}[dev]${C_RESET} %s\n" "$*" >&2; }
ok()    { printf "${C_GREEN}[dev]${C_RESET} %s\n" "$*"; }

# ----- dependency checks -----
need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    err "$1 is required but not installed"; exit 1
  fi
}

check_deps() {
  need_cmd docker
  need_cmd go
  need_cmd node
  need_cmd npm
  if [[ ! -d "$ROOT/solver/.venv" ]]; then
    warn "solver/.venv not found. Creating..."
    python3 -m venv "$ROOT/solver/.venv"
    "$ROOT/solver/.venv/bin/pip" install -q --upgrade pip
    "$ROOT/solver/.venv/bin/pip" install -q -r "$ROOT/solver/requirements.txt" eval_type_backport
  fi
  if [[ ! -d "$ROOT/web/node_modules" ]]; then
    warn "web/node_modules not found. Installing..."
    (cd "$ROOT/web" && npm install --silent)
  fi
}

# ----- PG / Redis -----
container_running() {
  [[ "$(docker inspect -f '{{.State.Running}}' "$1" 2>/dev/null || echo false)" == "true" ]]
}
container_exists() {
  docker inspect "$1" >/dev/null 2>&1
}

ensure_pg() {
  if container_exists "$PG_NAME"; then
    if container_running "$PG_NAME"; then
      info "postgres already running"
    else
      docker start "$PG_NAME" >/dev/null
      ok "postgres started"
    fi
  else
    info "creating postgres container..."
    docker run -d --name "$PG_NAME" -p 5432:5432 -e POSTGRES_PASSWORD="$PG_PASSWORD" postgres:16 >/dev/null
    sleep 2
    ok "postgres created"
  fi
  # wait until ready
  for i in {1..30}; do
    if docker exec "$PG_NAME" pg_isready -U postgres >/dev/null 2>&1; then return; fi
    sleep 0.5
  done
  err "postgres not ready after 15s"; exit 1
}

ensure_redis() {
  if container_exists "$REDIS_NAME"; then
    if ! container_running "$REDIS_NAME"; then
      docker start "$REDIS_NAME" >/dev/null
      ok "redis started"
    else
      info "redis already running"
    fi
  else
    info "creating redis container..."
    docker run -d --name "$REDIS_NAME" -p 6379:6379 redis:7-alpine >/dev/null
    ok "redis created"
  fi
}

ensure_db() {
  if docker exec "$PG_NAME" psql -U postgres -lqt 2>/dev/null | cut -d'|' -f1 | grep -qw "$DB_NAME"; then
    info "database $DB_NAME exists"
  else
    info "creating database $DB_NAME..."
    docker exec "$PG_NAME" psql -U postgres -c "CREATE DATABASE $DB_NAME;" >/dev/null
    docker exec -i "$PG_NAME" psql -U postgres -d "$DB_NAME" < "$ROOT/api/migrations/0001_init.sql" >/dev/null
    ok "migrations applied"
  fi
}

# ----- .env.local 자동 생성 -----
ensure_env_local() {
  if [[ -f "$ROOT/api/.env.local" ]]; then return; fi
  info "generating api/.env.local with random secrets..."
  local admin_email="${ADMIN_EMAIL_HINT:-admin@example.com}"
  cat > "$ROOT/api/.env.local" <<EOF
# Auto-generated by scripts/dev.sh — local dev only.
ENV=development
ALLOWED_ORIGINS=http://localhost:3000

DB_HOST=localhost
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=$PG_PASSWORD
DB_NAME=$DB_NAME
DB_SSLMODE=disable

REDIS_HOST=localhost:6379
REDIS_PASSWORD=

JWT_SECRET=$(openssl rand -hex 32)
JWT_ACCESS_TTL=1h
JWT_REFRESH_TTL=168h

SOLVER_URL=http://localhost:8000
SOLVER_INTERNAL_TOKEN=

ADMIN_EMAIL=$admin_email
SKIP_MIGRATE=1
PORT=8080
EOF
  ok "api/.env.local created — edit ADMIN_EMAIL to your Google email"
}

ensure_web_env() {
  if [[ -f "$ROOT/web/.env.local" ]]; then return; fi
  info "generating web/.env.local..."
  cp "$ROOT/web/.env.local.example" "$ROOT/web/.env.local"
  ok "web/.env.local created (NEXT_PUBLIC_DEV_LOGIN=1)"
}

# ----- process management -----
start_with_prefix() {
  # usage: start_with_prefix <name> <color> <cwd> <command...>
  local name=$1 color=$2 cwd=$3; shift 3
  (
    cd "$cwd"
    "$@" 2>&1 | sed -u -e "s|^|${color}[${name}]${C_RESET} |"
  ) &
  echo $! >> "$PIDS_FILE"
}

cleanup() {
  if [[ ! -f "$PIDS_FILE" ]]; then return; fi
  info "stopping services..."
  while read -r pid; do
    if [[ -n "$pid" ]] && kill -0 "$pid" 2>/dev/null; then
      # SIGTERM to process group
      kill -TERM "-$pid" 2>/dev/null || kill -TERM "$pid" 2>/dev/null || true
    fi
  done < "$PIDS_FILE"
  rm -f "$PIDS_FILE"
  ok "services stopped"
}

# ----- commands -----
cmd_init() {
  check_deps
  ensure_pg
  ensure_redis
  ensure_db
  ensure_env_local
  ensure_web_env
  ok "init complete. run: scripts/dev.sh up"
}

cmd_up() {
  check_deps
  ensure_pg
  ensure_redis
  ensure_db
  ensure_env_local
  ensure_web_env

  : > "$PIDS_FILE"
  trap cleanup EXIT INT TERM

  info "starting solver (port 8000)..."
  start_with_prefix solver "$C_PURPLE" "$ROOT/solver" \
    env ENV=development "$ROOT/solver/.venv/bin/uvicorn" app.main:app --port 8000 --reload

  sleep 1

  info "starting api (port 8080)..."
  start_with_prefix api "$C_BLUE" "$ROOT/api" \
    bash -c "set -a; source .env.local; set +a; go run ./cmd/server"

  sleep 2

  info "starting web (port 3000)..."
  start_with_prefix web "$C_GREEN" "$ROOT/web" \
    npm run dev

  echo ""
  ok "all services started. open ${C_CYAN}http://localhost:3000${C_RESET}"
  printf "   ${C_DIM}Ctrl+C to stop everything${C_RESET}\n"
  echo ""

  # wait for any child to exit
  wait
}

cmd_down() {
  cleanup
  if container_running "$PG_NAME"; then docker stop "$PG_NAME" >/dev/null; ok "postgres stopped"; fi
  if container_running "$REDIS_NAME"; then docker stop "$REDIS_NAME" >/dev/null; ok "redis stopped"; fi
  info "data preserved (use 'purge' to delete)"
}

cmd_status() {
  printf "${C_CYAN}=== containers ===${C_RESET}\n"
  for c in "$PG_NAME" "$REDIS_NAME"; do
    if container_running "$c"; then printf "  ${C_GREEN}●${C_RESET} %s\n" "$c"
    elif container_exists "$c"; then printf "  ${C_YELLOW}○${C_RESET} %s (stopped)\n" "$c"
    else printf "  ${C_DIM}-${C_RESET} %s (absent)\n" "$c"
    fi
  done
  printf "\n${C_CYAN}=== services ===${C_RESET}\n"
  declare -a svcs=(solver:8000 api:8080 web:3000)
  for entry in "${svcs[@]}"; do
    name=${entry%%:*}
    port=${entry##*:}
    code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 1 "http://localhost:$port/" 2>/dev/null || true)
    if [[ -z "$code" || "$code" == "000" ]]; then
      printf "  ${C_DIM}-${C_RESET} %s @ :%s\n" "$name" "$port"
    else
      printf "  ${C_GREEN}●${C_RESET} %s @ :%s (HTTP %s)\n" "$name" "$port" "$code"
    fi
  done
}

cmd_reset() {
  if ! container_running "$PG_NAME"; then ensure_pg; fi
  warn "truncating user data (seed/levels/settings 보존)..."
  docker exec -i "$PG_NAME" psql -U postgres -d "$DB_NAME" >/dev/null <<'SQL'
TRUNCATE schedule_cells, swap_requests, night_keeper_assignments, schedules, wishes, nurses RESTART IDENTITY CASCADE;
SQL
  ok "user data truncated"
}

cmd_purge() {
  cleanup
  for c in "$PG_NAME" "$REDIS_NAME"; do
    if container_exists "$c"; then docker rm -f "$c" >/dev/null && ok "removed $c"; fi
  done
  warn "data permanently deleted. run 'scripts/dev.sh init' to start over"
}

cmd_help() {
  cat <<EOF
ward-duty local dev orchestrator

  scripts/dev.sh up        모든 서비스 기동 (PG/Redis/solver/api/web, prefix 로그)
  scripts/dev.sh down      서비스 정지 (데이터 보존)
  scripts/dev.sh status    상태 확인
  scripts/dev.sh init      1회 셋업 (.env.local 자동 생성 + DB 마이그)
  scripts/dev.sh reset     DB user data 초기화 (seed 보존)
  scripts/dev.sh purge     컨테이너 완전 삭제 (데이터 영구 손실)
  scripts/dev.sh help      이 도움말

Tip:
  ADMIN_EMAIL_HINT=me@gmail.com scripts/dev.sh init
EOF
}

case "${1:-help}" in
  up)     cmd_up ;;
  down)   cmd_down ;;
  status) cmd_status ;;
  reset)  cmd_reset ;;
  purge)  cmd_purge ;;
  init)   cmd_init ;;
  help|-h|--help) cmd_help ;;
  *)      err "unknown command: $1"; cmd_help; exit 1 ;;
esac
